// Pip's Arcade — pure-fun board-vision mini-games. All `target` type (geometric,
// no engine): tap the piece, hop to the goals. Highly replayable; builds the
// "where can this piece go?" instinct that underlies all of chess.

import type { Lesson } from "../../types";

export const arcade: Lesson = {
  id: "kids-arcade",
  title: "Pip's Arcade",
  summary:
    "Game time! Hop, zoom, and gobble your way around the board. Play these as many times as you like!",
  activities: [
    {
      id: "arcade-knight-tour",
      type: "target",
      title: "Knight's Hop Tour",
      blurb: "Hop to every star!",
      piece: "knight",
      square: "b1",
      orientation: "white",
      targets: ["c3", "e4", "g5", "f7"],
      intro: "The knight loves to hop! Tap the knight and jump in L-shapes to collect all the stars.",
      successText: "Super hopping! You guided the knight all over the board. 🐴",
    },
    {
      id: "arcade-rook-roundup",
      type: "target",
      title: "Rook Roundup",
      blurb: "Zoom to the corners!",
      piece: "rook",
      square: "d4",
      orientation: "white",
      targets: ["a1", "h1", "h8", "a8"],
      intro: "Rooks zoom in straight lines. Tap the rook and collect the star in every corner!",
      successText: "Choo choo! You drove the rook to all four corners. 🚂",
    },
    {
      id: "arcade-bishop-diagonal",
      type: "target",
      title: "Bishop's Diagonal Dash",
      blurb: "Stay on your color!",
      piece: "bishop",
      square: "a1",
      orientation: "white",
      targets: ["c3", "e5", "g7"],
      intro: "The bishop only moves on slanted lines and stays on its own color. Slide up the big diagonal to grab every star!",
      successText: "Smooth slider! The bishop stayed on the dark squares the whole way. ⛪",
    },
    {
      id: "arcade-gobble-pawns",
      type: "target",
      title: "Gobble the Apples",
      blurb: "Munch them all!",
      piece: "knight",
      square: "d4",
      orientation: "white",
      targets: ["b5", "c6", "e6", "f5"],
      prey: "🍎",
      intro: "Yum! Tap the knight and hop onto every apple to gobble it up.",
      successText: "Munch munch — all gobbled up! 🍎",
    },
    {
      id: "arcade-rook-budget",
      type: "target",
      title: "Star in 3 Hops",
      blurb: "Can you do it fast?",
      piece: "rook",
      square: "a1",
      orientation: "white",
      targets: ["h8"],
      moveBudget: 3,
      intro: "Get the rook to the star in just 3 hops! Remember — rooks go in straight lines.",
      successText: "Speedy! You found a quick path to the star. ⭐",
    },
    {
      id: "arcade-king-dodge",
      type: "target",
      title: "Dodge to the Star",
      blurb: "Avoid the red squares!",
      piece: "king",
      square: "a1",
      orientation: "white",
      targets: ["a8"],
      avoidSquares: ["a4", "a5", "b4", "b5"],
      intro: "Walk the king up to the star — but don't step on a red square! Take little steps around them.",
      successText: "Careful stepping! You dodged every red square. 👑",
    },
  ],
};
