// Chess for Kids — Lesson 5: check and checkmate (interactive).

import type { Lesson } from "../../types";

export const l5: Lesson = {
  id: "kids-l5-check-mate",
  title: "5. Check and Checkmate",
  summary:
    "The whole game is about the king! Spot a check, give a check, escape a check — and tell checkmate from stalemate.",
  activities: [
    {
      id: "kids-l5-check-mate-concept",
      type: "concept",
      check: {
        question: "What is checkmate?",
        options: ["The king is attacked and cannot escape","The king is attacked but can move away","Nobody has any pieces left"],
        correctIndex: 0,
        explanation: "Checkmate ends the game — the king is in check with no way out!",
      },
      title: "Keep the King Safe",
      blurb: "Check and checkmate.",
      body: "When the king is attacked, that's a check, and he must get to safety. If he can't escape at all, that's checkmate and the game is won!",
    },
    {
      id: "is-it-check",
      type: "sort",
      title: "Is the king in check?",
      blurb: "Is the king under attack?",
      prompt: "Is the black king in CHECK right now?",
      fen: "4k3/8/8/8/8/8/8/4R1K1 b - - 0 1",
      orientation: "white",
      options: [
        { label: "Yes!", emoji: "⚠️" },
        { label: "No", emoji: "🙂" },
      ],
      correctIndex: 0,
      explanation: "Yes! The white rook attacks the king straight up the e-file. When your king is in check, you MUST get it to safety.",
    },
    {
      id: "give-check-1",
      dialogue: {
        intro: { speaker: "rookwell", mood: "idle", text: "Attack the enemy king — give check!" },
        onWrong: { speaker: "murk", mood: "sly", text: "Hee-hee! That's not check. Try again, hero." },
      },
      type: "puzzle",
      title: "Give a check!",
      blurb: "Attack the king in one move.",
      fen: "4k3/8/8/8/8/8/8/R5K1 w - - 0 1",
      orientation: "white",
      goal: { type: "check" },
      prompt: "Move your rook to give the king a check!",
      hints: ["A rook attacks along its row and column.", "Line up on the king's row."],
      successText: "Check! Your rook attacks the king. Now the king has to escape.",
      solution: ["a1a8"],
    },
    {
      id: "give-check-2",
      type: "puzzle",
      title: "Queen check!",
      blurb: "Use the queen this time.",
      fen: "4k3/8/8/8/8/8/8/3Q1K2 w - - 0 1",
      orientation: "white",
      goal: { type: "check" },
      prompt: "Move your queen to give the king a check!",
      hints: ["The queen can move straight or slanted.", "Get onto the king's row or file."],
      successText: "Check! The mighty queen attacks the king.",
      solution: ["d1d8"],
    },
    {
      id: "escape-check",
      type: "puzzle",
      title: "Get out of check!",
      blurb: "Your king is under attack!",
      fen: "k7/8/8/8/8/8/8/r3K3 w - - 0 1",
      orientation: "white",
      goal: { type: "escape" },
      prompt: "Your king is in check from the rook! Move it to a safe square.",
      hints: ["The rook attacks all along row 1.", "Step the king OFF the bottom row."],
      successText: "Safe! Moving the king is one of the three ways out of check (move, block, or capture).",
      solution: ["e1e2"],
    },
    {
      id: "mate-or-stale-1",
      type: "sort",
      title: "Checkmate or Stalemate?",
      blurb: "King in check with no escape?",
      prompt: "The black king can't move. Is this Checkmate or Stalemate?",
      fen: "3R2k1/5ppp/8/8/8/8/5PPP/6K1 b - - 0 1",
      orientation: "white",
      options: [
        { label: "Checkmate", emoji: "👑" },
        { label: "Stalemate", emoji: "🤝" },
      ],
      correctIndex: 0,
      explanation: "Checkmate! The king is IN check (from the rook) and can't escape. That's a win!",
    },
    {
      id: "mate-or-stale-2",
      type: "sort",
      title: "Checkmate or Stalemate?",
      blurb: "Tricky one!",
      prompt: "The black king can't move. Is this Checkmate or Stalemate?",
      fen: "7k/5Q2/6K1/8/8/8/8/8 b - - 0 1",
      orientation: "white",
      options: [
        { label: "Checkmate", emoji: "👑" },
        { label: "Stalemate", emoji: "🤝" },
      ],
      correctIndex: 1,
      explanation: "Stalemate — a tie! The king has no move but is NOT in check. Be careful not to do this when you're winning!",
    },
    {
      id: "mate-in-1-practice",
      type: "practiceSet",
      title: "Checkmate Practice",
      blurb: "Find checkmate in one!",
      intro: "Each puzzle has a checkmate in ONE move. Find 3 to master it!",
      requiredCorrect: 3,
      items: [
        {
          fen: "6k1/5ppp/8/8/8/8/5PPP/3R2K1 w - - 0 1",
          orientation: "white",
          goal: { type: "mate", inMoves: 1 },
          prompt: "Checkmate the trapped king with your rook!",
          solution: ["d1d8"],
        },
        {
          fen: "6k1/5ppp/8/8/8/8/5PPP/4Q1K1 w - - 0 1",
          orientation: "white",
          goal: { type: "mate", inMoves: 1 },
          prompt: "Use the queen for checkmate!",
          solution: ["e1e8"],
        },
        {
          fen: "k7/2Q5/2K5/8/8/8/8/8 w - - 0 1",
          orientation: "white",
          goal: { type: "mate", inMoves: 1 },
          prompt: "Bring the queen next to the king — your king guards her!",
          solution: ["c7b7"],
        },
        {
          fen: "7k/1R6/8/8/8/8/8/R3K3 w - - 0 1",
          orientation: "white",
          goal: { type: "mate", inMoves: 1 },
          prompt: "Two rooks make a ladder — deliver mate!",
          solution: ["a1a8"],
        },
      ],
    },
  ],
};
