// Render each extracted scene to a bespoke storybook illustration with Nano Banana
// Pro, into public/images/scenes/, and (re)write src/lib/art/sceneManifest.ts.
// Mirrors tts/generate-audio: incremental (skips scenes whose image exists),
// resumable, key-rotating, and it prunes stale images. Character consistency
// comes from feeding each scene's cast model sheets (scripts/scene-art/refs/) as
// reference images. Run (after `npm run art:extract` and `npm run art:cast`):
//   GEMINI_API_KEYS="<key>" npm run art:generate

import {
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { CHARACTERS } from "../../src/content/kids/characters";
import type { SceneEntry } from "./extract-scenes";
import { ImageGen, RefImage, extFor } from "./gen";
import { APPEARANCES, MOOD_HINT, SETTINGS, STYLE_BIBLE } from "./prompts";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(here, "..", "..");
const manifestPath = join(here, "manifest.json");
const refsDir = join(here, "refs");
const scenesDir = join(repoRoot, "public", "images", "scenes");
const sceneManifestPath = join(repoRoot, "src", "lib", "art", "sceneManifest.ts");

const name = (id: string) => CHARACTERS[id as keyof typeof CHARACTERS]?.name ?? id;

/** Build the full image prompt for a scene. */
function scenePrompt(e: SceneEntry): string {
  const setting = SETTINGS[e.backdrop] ?? e.backdrop;
  const focal = e.cast[0];
  const focalMood = e.lines.find((l) => l.speaker === focal)?.mood ?? "idle";
  const others = e.cast.slice(1);

  const castLines = e.cast.map((id) => `- ${APPEARANCES[id] ?? name(id)}`).join("\n");
  const beat = e.lines.map((l) => l.text).join(" ");

  return (
    `${STYLE_BIBLE}\n\n` +
    `Wide 16:9 storybook illustration set in ${setting}.\n\n` +
    `Characters in this scene (keep them ON-MODEL, matching the reference images):\n${castLines}\n\n` +
    (focal
      ? `Focal character: ${name(focal)}, ${MOOD_HINT[focalMood] ?? "expressive"}, placed clearly as the heart of the scene.` +
        (others.length ? ` Also present: ${others.map(name).join(", ")}.` : "") +
        "\n\n"
      : "") +
    `Story beat to convey through the characters' poses, expressions, and the setting ` +
    `(do NOT write any of these words in the image): "${beat}"\n\n` +
    `IMPORTANT: paint the ENTIRE scene in full, rich, saturated storybook color — even if the ` +
    `story text mentions grey, lost color, or a "Grey" spell. Do NOT desaturate, grey out, or ` +
    `drain color from the image; color drain is handled separately by the app. ` +
    `Warm and inviting, one clear focal point, gentle depth. No text, letters, or words anywhere.`
  );
}

/** Load the cast refs once: characterId → reference image (base64). */
function loadRefs(): Record<string, RefImage> {
  const refs: Record<string, RefImage> = {};
  if (!existsSync(refsDir)) return refs;
  for (const f of readdirSync(refsDir)) {
    const m = f.match(/^([a-z]+)\.(png|jpg|jpeg|webp)$/i);
    if (!m) continue;
    const mime = m[2].toLowerCase() === "png" ? "image/png" : m[2].toLowerCase() === "webp" ? "image/webp" : "image/jpeg";
    refs[m[1]] = { mime, base64: readFileSync(join(refsDir, f)).toString("base64") };
  }
  return refs;
}

function rewriteManifest(manifest: SceneEntry[]) {
  // Map STABLE sceneId → filename, from what's actually on disk. Prune orphans.
  const keyToScene = new Map(manifest.map((e) => [e.key, e.sceneId]));
  const present = existsSync(scenesDir) ? readdirSync(scenesDir) : [];
  const bySceneId: Record<string, string> = {};
  for (const f of present) {
    const stem = f.replace(/\.(png|jpg|jpeg|webp)$/i, "");
    const sceneId = keyToScene.get(stem);
    if (sceneId) bySceneId[sceneId] = f;
    else {
      rmSync(join(scenesDir, f));
      console.log(`· pruned orphan ${f}`);
    }
  }
  const body = Object.keys(bySceneId)
    .sort()
    .map((k) => `  ${JSON.stringify(k)}: ${JSON.stringify(bySceneId[k])},`)
    .join("\n");
  writeFileSync(
    sceneManifestPath,
    `// AUTO-GENERATED by scripts/scene-art/generate-scenes.ts — do not edit by hand.\n` +
      `// Maps a story scene id (SceneActivity.id, e.g. "kids-l1-board-hook") to its\n` +
      `// bespoke illustration filename under public/images/scenes/. Empty until\n` +
      `// \`npm run art:generate\` has rendered images; while a scene has no entry, SceneArt\n` +
      `// falls back to its inline-SVG backdrop (so the app always renders).\n` +
      `export const SCENE_IMAGES: Record<string, string> = {\n${body}\n};\n`,
  );
  return Object.keys(bySceneId).length;
}

async function main() {
  if (!existsSync(manifestPath)) {
    console.error("No manifest.json — run `npm run art:extract` first.");
    process.exit(1);
  }
  const manifest: SceneEntry[] = JSON.parse(readFileSync(manifestPath, "utf8"));
  mkdirSync(scenesDir, { recursive: true });
  const refs = loadRefs();
  if (!Object.keys(refs).length) {
    console.warn("⚠ No character refs in scripts/scene-art/refs/ — run `npm run art:cast` first for consistency.\n");
  }
  const gen = new ImageGen();

  // Optional scene-id filter: `npm run art:generate -- <sceneId> <sceneId> …`
  // renders only those scenes (samples, re-rolls). No args = all missing scenes.
  const only = new Set(process.argv.slice(2).filter((a) => !a.startsWith("-")));
  const wanted = (e: SceneEntry) => only.size === 0 || only.has(e.sceneId);

  const onDisk = new Set(readdirSync(scenesDir).map((f) => f.replace(/\.(png|jpg|jpeg|webp)$/i, "")));
  const todo = manifest.filter((e) => !onDisk.has(e.key) && wanted(e)).length;
  console.log(
    `Rendering ${todo} scene(s) on the image model ` +
      `(${manifest.length - todo} already done · ${manifest.length} total · ${gen.keyCount} key(s)).\n`,
  );

  let made = 0;
  let reused = 0;
  for (const e of manifest) {
    if (onDisk.has(e.key)) {
      reused++;
      continue;
    }
    if (!wanted(e)) continue;
    const sceneRefs = e.cast.map((id) => refs[id]).filter(Boolean) as RefImage[];
    const res = await gen.generate(scenePrompt(e), sceneRefs);
    if (gen.capped) break;
    if (!res) {
      console.error(`✗ ${e.sceneId}: no image`);
      continue;
    }
    const file = `${e.key}.${extFor(res.mime)}`;
    writeFileSync(join(scenesDir, file), res.bytes);
    made++;
    const done = made + reused;
    const pct = Math.round((done / manifest.length) * 100);
    console.log(
      `[${String(done).padStart(2)}/${manifest.length}] ${String(pct).padStart(3)}% ` +
        `${gen.keyLabel} ✓ ${e.sceneId} (${Math.round(res.bytes.length / 1024)}KB)`,
    );
  }

  const total = rewriteManifest(manifest);
  console.log(`\nDone: ${made} generated, ${reused} reused, ${total}/${manifest.length} scenes illustrated.`);
}

void main();
