// Render painted character HEADSHOTS (for the dialogue chip / quest-map / chapter
// covers) and PIP MASCOT poses (reward/footer), matching the approved cast model
// sheets. Mirrors generate-scenes: conditioned on refs/, skips existing, rebuilds
// src/lib/art/portraitManifest.ts. Run (after `npm run art:cast`):
//   GEMINI_API_KEYS="<key>" npm run art:portraits        # all
//   GEMINI_API_KEYS="<key>" npm run art:portraits -- pip cheer   # subset

import {
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { ImageGen, RefImage, extFor } from "./gen";
import { APPEARANCES, STYLE_BIBLE } from "./prompts";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(here, "..", "..");
const refsDir = join(here, "refs");
const charsDir = join(repoRoot, "public", "images", "characters");
const mascotDir = join(repoRoot, "public", "images", "mascot");
const manifestPath = join(repoRoot, "src", "lib", "art", "portraitManifest.ts");

const MASCOT_MOODS: Record<string, string> = {
  idle: "standing happily and friendly, calm",
  cheer: "cheering with both little arms raised, joyful and excited, rosy cheeks",
  think: "thinking with one hand to the chin, curious and bright-eyed",
};

function headshotPrompt(appearance: string): string {
  return (
    `${STYLE_BIBLE}\n\n` +
    `A friendly circular bust portrait (head and a little of the shoulders) of ${appearance}. ` +
    `Facing forward with a warm, gentle smile, centered, full color, on a soft simple cream ` +
    `background. Keep the character exactly on-model with the reference image. No text.`
  );
}
function mascotPrompt(pose: string): string {
  return (
    `${STYLE_BIBLE}\n\n` +
    `Full-body illustration of ${APPEARANCES.pip}, ${pose}. ` +
    `Centered, on a plain solid PURE WHITE (#ffffff) background, no ground line, no cast shadow, ` +
    `no backdrop, no checkerboard — just Pip on flat white so the background can be removed cleanly. ` +
    `Keep Pip exactly on-model with the reference image. No text.`
  );
}

/** Load a single ref image (characterId → base64), if present. */
function loadRef(id: string): RefImage[] {
  if (!existsSync(refsDir)) return [];
  const f = readdirSync(refsDir).find((n) => n.match(new RegExp(`^${id}\\.(png|jpg|jpeg|webp)$`, "i")));
  if (!f) return [];
  const ext = f.split(".").pop()!.toLowerCase();
  const mime = ext === "png" ? "image/png" : ext === "webp" ? "image/webp" : "image/jpeg";
  return [{ mime, base64: readFileSync(join(refsDir, f)).toString("base64") }];
}

function rewriteManifest() {
  const charFiles = existsSync(charsDir) ? readdirSync(charsDir) : [];
  const mascotFiles = existsSync(mascotDir) ? readdirSync(mascotDir) : [];
  const chars: Record<string, string> = {};
  for (const f of charFiles) {
    const m = f.match(/^([a-z]+)\.(png|jpg|jpeg|webp)$/i);
    if (m) chars[m[1]] = f;
  }
  const mascot: Record<string, string> = {};
  for (const f of mascotFiles) {
    const m = f.match(/^pip-([a-z]+)\.(png|jpg|jpeg|webp)$/i);
    if (m) mascot[m[1]] = f;
  }
  const obj = (o: Record<string, string>) =>
    Object.keys(o)
      .sort()
      .map((k) => `  ${JSON.stringify(k)}: ${JSON.stringify(o[k])},`)
      .join("\n");
  writeFileSync(
    manifestPath,
    `// AUTO-GENERATED by scripts/scene-art/generate-portraits.ts — do not edit by hand.\n` +
      `// Painted character headshots (public/images/characters/<id>.*) and Pip mascot poses\n` +
      `// (public/images/mascot/pip-<mood>.*). Empty entries fall back to inline SVG.\n` +
      `export const CHARACTER_IMAGES: Record<string, string> = {\n${obj(chars)}\n};\n\n` +
      `export const PIP_MASCOT_IMAGES: Record<string, string> = {\n${obj(mascot)}\n};\n`,
  );
  return { chars: Object.keys(chars).length, mascot: Object.keys(mascot).length };
}

async function main() {
  mkdirSync(charsDir, { recursive: true });
  mkdirSync(mascotDir, { recursive: true });
  const only = new Set(process.argv.slice(2).filter((a) => !a.startsWith("-")));
  const want = (name: string) => only.size === 0 || only.has(name);
  const gen = new ImageGen();

  // Headshots: every character (incl. caller).
  for (const id of Object.keys(APPEARANCES)) {
    if (!want(id)) continue;
    if (readdirSync(charsDir).some((f) => f.startsWith(`${id}.`))) continue;
    const res = await gen.generate(headshotPrompt(APPEARANCES[id]), loadRef(id), "1:1");
    if (gen.capped) break;
    if (!res) { console.error(`✗ headshot ${id}`); continue; }
    writeFileSync(join(charsDir, `${id}.${extFor(res.mime)}`), res.bytes);
    console.log(`✓ headshot ${id} (${Math.round(res.bytes.length / 1024)}KB)`);
  }
  // Pip mascot poses.
  for (const mood of Object.keys(MASCOT_MOODS)) {
    if (!want(mood)) continue;
    if (readdirSync(mascotDir).some((f) => f.startsWith(`pip-${mood}.`))) continue;
    const res = await gen.generate(mascotPrompt(MASCOT_MOODS[mood]), loadRef("pip"), "1:1");
    if (gen.capped) break;
    if (!res) { console.error(`✗ mascot ${mood}`); continue; }
    writeFileSync(join(mascotDir, `pip-${mood}.${extFor(res.mime)}`), res.bytes);
    console.log(`✓ mascot pip-${mood} (${Math.round(res.bytes.length / 1024)}KB)`);
  }

  const n = rewriteManifest();
  console.log(`\nManifest: ${n.chars} headshots, ${n.mascot} mascot poses.`);
}

void main();
