// Standalone tactics bank — engine-verified, explicitly-tagged puzzles that feed
// the Tactics Trainer + Daily Puzzle pool WITHOUT living inside a lesson module.
// Every entry is verified sound + uniquely-best by `npm run validate` (which runs
// the same Stockfish soundness/uniqueness checks as for module puzzles). Add more
// here over time to grow the pool; tags are explicit (no heuristic derivation).
//
// All positions are original/generic tactical motifs (public chess knowledge).

import type { PuzzleTheme, Difficulty } from "./puzzles";
import type { Orientation, PuzzleGoal } from "./types";

export interface BankPuzzle {
  id: string;
  fen: string;
  orientation: Orientation;
  solution: string[];
  goal: PuzzleGoal;
  theme: PuzzleTheme;
  difficulty: Difficulty;
  prompt: string;
}

export const TACTICS_BANK: BankPuzzle[] = [
  {
    id: "tb-backrank-1",
    fen: "6k1/5ppp/8/8/8/8/3R2PP/6K1 w - - 0 1",
    orientation: "white",
    solution: ["d2d8"],
    goal: { type: "mate", inMoves: 1 },
    theme: "back-rank",
    difficulty: 1,
    prompt: "White to play and mate in one — the back rank is fatally weak.",
  },
  {
    id: "tb-backrank-2",
    fen: "6k1/5ppp/8/8/8/8/4R1PP/6K1 w - - 0 1",
    orientation: "white",
    solution: ["e2e8"],
    goal: { type: "mate", inMoves: 1 },
    theme: "back-rank",
    difficulty: 1,
    prompt: "White to play and mate in one.",
  },
  {
    id: "tb-royal-fork-1",
    fen: "2q3k1/pp3ppp/8/3N4/8/8/PP3PPP/6K1 w - - 0 1",
    orientation: "white",
    solution: ["d5e7", "g8f8", "e7c8"],
    goal: { type: "win-material", minGain: 3 },
    theme: "fork",
    difficulty: 2,
    prompt: "White to play and win the queen with a knight fork.",
  },
  {
    id: "tb-hanging-queen-1",
    fen: "6k1/6pp/8/q7/8/8/5PPP/R5K1 w - - 0 1",
    orientation: "white",
    solution: ["a1a5"],
    goal: { type: "win-material", minGain: 3 },
    theme: "win-material",
    difficulty: 1,
    prompt: "White to play — the black queen is undefended. Win it.",
  },
  {
    id: "tb-skewer-queen-1",
    fen: "k7/8/8/q7/8/8/8/R6K w - - 0 1",
    orientation: "white",
    solution: ["a1a5"],
    goal: { type: "win-material", minGain: 3 },
    theme: "skewer",
    difficulty: 1,
    prompt: "White to play and win the queen down the open file.",
  },
  {
    id: "tb-hanging-rook-1",
    fen: "4k3/8/8/8/r7/8/8/R3K3 w - - 0 1",
    orientation: "white",
    solution: ["a1a4"],
    goal: { type: "win-material", minGain: 3 },
    theme: "win-material",
    difficulty: 1,
    prompt: "White to play and win the rook.",
  },
  {
    id: "tb-discovered-1",
    fen: "3qk3/8/8/4N3/8/8/8/4R1K1 w - - 0 1",
    orientation: "white",
    solution: ["e5c6", "e8d7", "c6d8"],
    goal: { type: "win-material", minGain: 3 },
    theme: "discovered",
    difficulty: 2,
    prompt: "White to play — a discovered check wins the queen.",
  },
  {
    id: "tb-skewer-rook-1",
    fen: "6k1/6pp/8/8/8/r7/6PP/R5K1 w - - 0 1",
    orientation: "white",
    solution: ["a1a3"],
    goal: { type: "win-material", minGain: 3 },
    theme: "skewer",
    difficulty: 1,
    prompt: "White to play and win the rook on the open file.",
  },
  {
    id: "tb-hanging-bishop-1",
    fen: "6k1/6pp/8/8/8/2b5/2R3PP/6K1 w - - 0 1",
    orientation: "white",
    solution: ["c2c3"],
    goal: { type: "win-material", minGain: 2 },
    theme: "win-material",
    difficulty: 1,
    prompt: "White to play and win the undefended bishop.",
  },
  {
    id: "tb-knight-grabs-queen-1",
    fen: "q3k3/8/1N6/8/8/8/PP3PPP/4K3 w - - 0 1",
    orientation: "white",
    solution: ["b6a8"],
    goal: { type: "win-material", minGain: 3 },
    theme: "fork",
    difficulty: 1,
    prompt: "White to play — the knight wins the queen.",
  },
  {
    id: "tb-kr-mate-1",
    fen: "6k1/8/6K1/8/8/8/8/R7 w - - 0 1",
    orientation: "white",
    solution: ["a1a8"],
    goal: { type: "mate", inMoves: 1 },
    theme: "mate",
    difficulty: 1,
    prompt: "White to play and mate in one — king and rook box the enemy in.",
  },
  {
    id: "tb-kr-mate-2",
    fen: "k7/8/1K6/8/8/8/8/7R w - - 0 1",
    orientation: "white",
    solution: ["h1h8"],
    goal: { type: "mate", inMoves: 1 },
    theme: "mate",
    difficulty: 1,
    prompt: "White to play and mate in one.",
  },
  {
    id: "tb-hanging-knight-1",
    fen: "4k3/8/4n3/8/8/8/4R3/4K3 w - - 0 1",
    orientation: "white",
    solution: ["e2e6"],
    goal: { type: "win-material", minGain: 2 },
    theme: "win-material",
    difficulty: 1,
    prompt: "White to play and win the knight with check.",
  },
  {
    id: "tb-gen-win-material-1",
    fen: "1R6/K3n3/3k4/4p3/8/1Q6/8/2q5 w - - 0 1",
    orientation: "white",
    solution: ["b8d8"],
    goal: { type: "win-material", minGain: 5 },
    theme: "win-material",
    difficulty: 2,
    prompt: "White to play and win material.",
  },
  {
    id: "tb-gen-mate-1",
    fen: "8/2p4K/1p6/8/3R4/1R6/6k1/8 w - - 0 1",
    orientation: "white",
    solution: ["d4d2", "g2h1", "b3b1"],
    goal: { type: "mate", inMoves: 2 },
    theme: "mate",
    difficulty: 2,
    prompt: "White to play and force mate in two.",
  },
  {
    id: "tb-gen-win-material-2",
    fen: "8/2k5/8/P1p5/8/5Rq1/K6N/8 w - - 0 1",
    orientation: "white",
    solution: ["f3g3"],
    goal: { type: "win-material", minGain: 5 },
    theme: "win-material",
    difficulty: 1,
    prompt: "White to play and win material.",
  },
  {
    id: "tb-gen-win-material-3",
    fen: "n7/8/1q2k1p1/6Q1/N7/P7/4K3/8 w - - 0 1",
    orientation: "white",
    solution: ["a4b6"],
    goal: { type: "win-material", minGain: 5 },
    theme: "win-material",
    difficulty: 1,
    prompt: "White to play and win material.",
  },
  {
    id: "tb-gen-win-material-4",
    fen: "8/8/Pp6/5k2/8/4K3/3N4/2b5 w - - 0 1",
    orientation: "white",
    solution: ["e3d3"],
    goal: { type: "win-material", minGain: 5 },
    theme: "win-material",
    difficulty: 2,
    prompt: "White to play and win material.",
  },
  {
    id: "tb-gen-win-material-5",
    fen: "3B2k1/8/8/1K3n2/6p1/7P/3r1R2/8 w - - 0 1",
    orientation: "white",
    solution: ["f2d2"],
    goal: { type: "win-material", minGain: 2 },
    theme: "win-material",
    difficulty: 1,
    prompt: "White to play and win material.",
  },
  {
    id: "tb-gen-mate-2",
    fen: "8/1b6/5R2/8/8/7Q/2P2p1K/2rk4 w - - 0 1",
    orientation: "white",
    solution: ["h3d3", "d1e1", "f6e6", "b7e4", "e6e4"],
    goal: { type: "mate", inMoves: 3 },
    theme: "mate",
    difficulty: 3,
    prompt: "White to play and force mate in three.",
  },
  {
    id: "tb-gen-win-material-6",
    fen: "3Q4/4qN2/8/8/7p/1b3k2/8/K7 w - - 0 1",
    orientation: "white",
    solution: ["d8e7"],
    goal: { type: "win-material", minGain: 5 },
    theme: "win-material",
    difficulty: 1,
    prompt: "White to play and win material.",
  },
  {
    id: "tb-gen-win-material-7",
    fen: "6r1/2P5/K1Q5/p3b3/8/8/8/6k1 w - - 0 1",
    orientation: "white",
    solution: ["c6c1"],
    goal: { type: "win-material", minGain: 5 },
    theme: "win-material",
    difficulty: 2,
    prompt: "White to play and win material.",
  },
  {
    id: "tb-gen-win-material-8",
    fen: "5nK1/8/8/8/4P3/8/2k1n3/7R w - - 0 1",
    orientation: "white",
    solution: ["g8f8"],
    goal: { type: "win-material", minGain: 2 },
    theme: "win-material",
    difficulty: 1,
    prompt: "White to play and win material.",
  },
  {
    id: "tb-gen-win-material-9",
    fen: "8/2p4k/8/7K/N5r1/2p2P2/1N6/8 w - - 0 1",
    orientation: "white",
    solution: ["f3g4"],
    goal: { type: "win-material", minGain: 5 },
    theme: "win-material",
    difficulty: 1,
    prompt: "White to play and win material.",
  },
  {
    id: "tb-gen-win-material-10",
    fen: "7r/8/8/8/3k4/8/7R/4K3 w - - 0 1",
    orientation: "white",
    solution: ["h2h8"],
    goal: { type: "win-material", minGain: 3 },
    theme: "win-material",
    difficulty: 1,
    prompt: "White to play and win material.",
  },
  {
    id: "tb-gen-win-material-11",
    fen: "8/1B3p2/5P2/7K/8/8/1P6/3k3b w - - 0 1",
    orientation: "white",
    solution: ["b7h1"],
    goal: { type: "win-material", minGain: 5 },
    theme: "win-material",
    difficulty: 1,
    prompt: "White to play and win material.",
  },
  {
    id: "tb-gen-back-rank-1",
    fen: "3k4/3P4/2R1K1n1/3p4/8/8/8/q7 w - - 0 1",
    orientation: "white",
    solution: ["c6c8"],
    goal: { type: "mate", inMoves: 1 },
    theme: "back-rank",
    difficulty: 1,
    prompt: "White to play and mate in one.",
  },
  {
    id: "tb-gen-mate-3",
    fen: "8/4Q3/4b2k/5B2/3P4/8/8/K7 w - - 0 1",
    orientation: "white",
    solution: ["e7f6", "h6h5", "f6g6", "h5h4", "g6g4"],
    goal: { type: "mate", inMoves: 3 },
    theme: "mate",
    difficulty: 3,
    prompt: "White to play and force mate in three.",
  },
  {
    id: "tb-gen-win-material-12",
    fen: "8/3k2P1/8/7r/8/K7/8/2B5 w - - 0 1",
    orientation: "white",
    solution: ["g7g8q"],
    goal: { type: "win-material", minGain: 5 },
    theme: "win-material",
    difficulty: 2,
    prompt: "White to play and win material.",
  },
  {
    id: "tb-gen-win-material-13",
    fen: "3N4/5K2/8/P7/4n1k1/3p4/5R2/5r2 w - - 0 1",
    orientation: "white",
    solution: ["f2f1"],
    goal: { type: "win-material", minGain: 3 },
    theme: "win-material",
    difficulty: 1,
    prompt: "White to play and win material.",
  },
  {
    id: "tb-gen-mate-4",
    fen: "1N6/8/8/5K2/7k/8/nnQ5/8 w - - 0 1",
    orientation: "white",
    solution: ["c2h2"],
    goal: { type: "mate", inMoves: 1 },
    theme: "mate",
    difficulty: 1,
    prompt: "White to play and mate in one.",
  },
  {
    id: "tb-gen-win-material-14",
    fen: "8/8/7n/k1B5/r5R1/2K3P1/8/8 w - - 0 1",
    orientation: "white",
    solution: ["c5b4"],
    goal: { type: "win-material", minGain: 2 },
    theme: "win-material",
    difficulty: 2,
    prompt: "White to play and win material.",
  },
  {
    id: "tb-gen-win-material-15",
    fen: "8/5p2/1r6/2B5/8/5K2/2k5/r4Q2 w - - 0 1",
    orientation: "white",
    solution: ["f1c4"],
    goal: { type: "win-material", minGain: 5 },
    theme: "win-material",
    difficulty: 2,
    prompt: "White to play and win material.",
  },
  {
    id: "tb-gen-mate-5",
    fen: "4r3/8/8/4P2b/1Q3R2/7k/5K1P/8 w - - 0 1",
    orientation: "white",
    solution: ["f4h4"],
    goal: { type: "mate", inMoves: 1 },
    theme: "mate",
    difficulty: 1,
    prompt: "White to play and mate in one.",
  },
  {
    id: "tb-gen-back-rank-2",
    fen: "8/5K1R/8/8/8/5R2/p6r/2k5 w - - 0 1",
    orientation: "white",
    solution: ["h7h2", "a2a1q", "f3f1"],
    goal: { type: "mate", inMoves: 2 },
    theme: "back-rank",
    difficulty: 2,
    prompt: "White to play and force mate in two.",
  },
  {
    id: "tb-gen-mate-6",
    fen: "7K/4R3/1Q1p4/8/8/k2r4/8/r7 w - - 0 1",
    orientation: "white",
    solution: ["e7a7"],
    goal: { type: "mate", inMoves: 1 },
    theme: "mate",
    difficulty: 1,
    prompt: "White to play and mate in one.",
  },
  {
    id: "tb-gen-win-material-16",
    fen: "8/8/6nK/k7/1p4B1/3P4/8/8 w - - 0 1",
    orientation: "white",
    solution: ["h6g6"],
    goal: { type: "win-material", minGain: 5 },
    theme: "win-material",
    difficulty: 1,
    prompt: "White to play and win material.",
  },
  {
    id: "tb-gen-mate-7",
    fen: "2K3Qb/4P3/3p4/8/3R4/8/8/7k w - - 0 1",
    orientation: "white",
    solution: ["d4h4"],
    goal: { type: "mate", inMoves: 1 },
    theme: "mate",
    difficulty: 1,
    prompt: "White to play and mate in one.",
  },
  {
    id: "tb-gen-win-material-17",
    fen: "8/P2k4/1r3P2/4p3/8/4K3/3p1R2/8 w - - 0 1",
    orientation: "white",
    solution: ["f2d2"],
    goal: { type: "win-material", minGain: 5 },
    theme: "win-material",
    difficulty: 1,
    prompt: "White to play and win material.",
  },
  {
    id: "tb-gen-fork-1",
    fen: "1r6/8/5N1P/4k3/7N/7P/K7/5n2 w - - 0 1",
    orientation: "white",
    solution: ["f6d7"],
    goal: { type: "win-material", minGain: 3 },
    theme: "fork",
    difficulty: 2,
    prompt: "White to play — a knight fork wins material.",
  },
  {
    id: "tb-gen-win-material-18",
    fen: "3r4/B3R3/8/1k2K1P1/3r4/8/8/8 w - - 0 1",
    orientation: "white",
    solution: ["a7d4"],
    goal: { type: "win-material", minGain: 3 },
    theme: "win-material",
    difficulty: 1,
    prompt: "White to play and win material.",
  },
  {
    id: "tb-gen-mate-8",
    fen: "8/3n1Rq1/3p4/1K2k3/3p4/3Q4/8/8 w - - 0 1",
    orientation: "white",
    solution: ["d3f5"],
    goal: { type: "mate", inMoves: 1 },
    theme: "mate",
    difficulty: 1,
    prompt: "White to play and mate in one.",
  },
  {
    id: "tb-gen-back-rank-3",
    fen: "3k4/2b5/2K5/7R/8/6P1/8/4Q1r1 w - - 0 1",
    orientation: "white",
    solution: ["h5h8"],
    goal: { type: "mate", inMoves: 1 },
    theme: "back-rank",
    difficulty: 1,
    prompt: "White to play and mate in one.",
  },
  {
    id: "tb-gen-win-material-19",
    fen: "8/4P3/3k4/1p6/8/5B2/5R1q/5K2 w - - 0 1",
    orientation: "white",
    solution: ["e7e8q"],
    goal: { type: "win-material", minGain: 5 },
    theme: "win-material",
    difficulty: 2,
    prompt: "White to play and win material.",
  },
  {
    id: "tb-gen-win-material-20",
    fen: "8/p7/6n1/1Qr3k1/8/8/8/4K3 w - - 0 1",
    orientation: "white",
    solution: ["b5c5"],
    goal: { type: "win-material", minGain: 3 },
    theme: "win-material",
    difficulty: 1,
    prompt: "White to play and win material.",
  },
  {
    id: "tb-gen-mate-9",
    fen: "R7/8/8/5R2/4n3/8/2K5/4k3 w - - 0 1",
    orientation: "white",
    solution: ["a8e8", "e1e2", "e8e4"],
    goal: { type: "mate", inMoves: 2 },
    theme: "mate",
    difficulty: 2,
    prompt: "White to play and force mate in two.",
  },
  {
    id: "tb-gen-win-material-21",
    fen: "7R/8/p1k4n/8/3K4/8/8/8 w - - 0 1",
    orientation: "white",
    solution: ["h8h6"],
    goal: { type: "win-material", minGain: 2 },
    theme: "win-material",
    difficulty: 1,
    prompt: "White to play and win material.",
  },
  {
    id: "tb-gen-mate-10",
    fen: "3k1N2/8/P3Q3/8/8/K2b4/8/8 w - - 0 1",
    orientation: "white",
    solution: ["e6d7"],
    goal: { type: "mate", inMoves: 1 },
    theme: "mate",
    difficulty: 1,
    prompt: "White to play and mate in one.",
  },
  {
    id: "tb-gen-win-material-22",
    fen: "6K1/2p1q3/8/2Q1P3/b7/8/1k6/3B4 w - - 0 1",
    orientation: "white",
    solution: ["c5e7"],
    goal: { type: "win-material", minGain: 5 },
    theme: "win-material",
    difficulty: 1,
    prompt: "White to play and win material.",
  },
  {
    id: "tb-gen-win-material-23",
    fen: "3K3N/8/6p1/8/5b1R/2r1P3/2k5/8 w - - 0 1",
    orientation: "white",
    solution: ["e3f4"],
    goal: { type: "win-material", minGain: 3 },
    theme: "win-material",
    difficulty: 1,
    prompt: "White to play and win material.",
  },
  {
    id: "tb-gen-win-material-24",
    fen: "2N5/8/n7/6P1/8/8/4K3/k7 w - - 0 1",
    orientation: "white",
    solution: ["g5g6"],
    goal: { type: "win-material", minGain: 5 },
    theme: "win-material",
    difficulty: 2,
    prompt: "White to play and win material.",
  },
  {
    id: "tb-gen-win-material-25",
    fen: "4n3/b7/3P4/8/1B6/8/1K2P3/5k2 w - - 0 1",
    orientation: "white",
    solution: ["d6d7"],
    goal: { type: "win-material", minGain: 3 },
    theme: "win-material",
    difficulty: 2,
    prompt: "White to play and win material.",
  },
  {
    id: "tb-gen-mate-11",
    fen: "6R1/8/3K4/1k2P3/8/4Q3/7q/5n2 w - - 0 1",
    orientation: "white",
    solution: ["e3b3", "b5a6", "g8a8"],
    goal: { type: "mate", inMoves: 2 },
    theme: "mate",
    difficulty: 2,
    prompt: "White to play and force mate in two.",
  },
  {
    id: "tb-gen-win-material-26",
    fen: "8/Q7/6K1/8/r1k5/3r2p1/1B6/8 w - - 0 1",
    orientation: "white",
    solution: ["a7a4"],
    goal: { type: "win-material", minGain: 5 },
    theme: "win-material",
    difficulty: 1,
    prompt: "White to play and win material.",
  },
  {
    id: "tb-gen-mate-12",
    fen: "8/1R5K/k4r2/8/3Q4/3P4/8/8 w - - 0 1",
    orientation: "white",
    solution: ["d4a7"],
    goal: { type: "mate", inMoves: 1 },
    theme: "mate",
    difficulty: 1,
    prompt: "White to play and mate in one.",
  },
  {
    id: "tb-gen-win-material-27",
    fen: "8/4K2N/P7/2n5/p7/3k4/8/8 w - - 0 1",
    orientation: "white",
    solution: ["a6a7"],
    goal: { type: "win-material", minGain: 3 },
    theme: "win-material",
    difficulty: 2,
    prompt: "White to play and win material.",
  },
  {
    id: "tb-gen-mate-13",
    fen: "8/4R3/7k/8/8/3R2K1/p7/5b2 w - - 0 1",
    orientation: "white",
    solution: ["d3d6", "h6h5", "e7e5"],
    goal: { type: "mate", inMoves: 2 },
    theme: "mate",
    difficulty: 2,
    prompt: "White to play and force mate in two.",
  },
  {
    id: "tb-gen-back-rank-4",
    fen: "6b1/8/1PK2P2/8/5R2/8/7R/2k5 w - - 0 1",
    orientation: "white",
    solution: ["f4f1"],
    goal: { type: "mate", inMoves: 1 },
    theme: "back-rank",
    difficulty: 1,
    prompt: "White to play and mate in one.",
  },
  {
    id: "tb-gen-mate-14",
    fen: "8/1R4K1/5r2/8/k7/8/8/2R5 w - - 0 1",
    orientation: "white",
    solution: ["c1a1"],
    goal: { type: "mate", inMoves: 1 },
    theme: "mate",
    difficulty: 1,
    prompt: "White to play and mate in one.",
  },
  {
    id: "tb-gen-win-material-28",
    fen: "8/8/q7/1N6/k3P3/2K5/3n4/4Q3 w - - 0 1",
    orientation: "white",
    solution: ["e1a1"],
    goal: { type: "win-material", minGain: 5 },
    theme: "win-material",
    difficulty: 2,
    prompt: "White to play and win material.",
  },
  {
    id: "tb-gen-win-material-29",
    fen: "8/6K1/8/1P5k/1B5p/8/8/7n w - - 0 1",
    orientation: "white",
    solution: ["b5b6"],
    goal: { type: "win-material", minGain: 3 },
    theme: "win-material",
    difficulty: 2,
    prompt: "White to play and win material.",
  },
  {
    id: "tb-gen-win-material-30",
    fen: "1K6/8/1Q1r4/3p4/4p2P/6n1/8/7k w - - 0 1",
    orientation: "white",
    solution: ["b6d6"],
    goal: { type: "win-material", minGain: 3 },
    theme: "win-material",
    difficulty: 1,
    prompt: "White to play and win material.",
  },
  {
    id: "tb-gen-mate-15",
    fen: "8/4p3/5R2/7k/3r3P/7K/7Q/8 w - - 0 1",
    orientation: "white",
    solution: ["h2e5"],
    goal: { type: "mate", inMoves: 1 },
    theme: "mate",
    difficulty: 1,
    prompt: "White to play and mate in one.",
  },
  {
    id: "tb-gen-win-material-31",
    fen: "8/1P1K4/6Bk/r7/8/8/5P2/8 w - - 0 1",
    orientation: "white",
    solution: ["b7b8q"],
    goal: { type: "win-material", minGain: 5 },
    theme: "win-material",
    difficulty: 2,
    prompt: "White to play and win material.",
  },
  {
    id: "tb-gen-win-material-32",
    fen: "8/8/1P6/8/8/2r5/2rR2K1/N1k5 w - - 0 1",
    orientation: "white",
    solution: ["d2c2"],
    goal: { type: "win-material", minGain: 5 },
    theme: "win-material",
    difficulty: 1,
    prompt: "White to play and win material.",
  },
  {
    id: "tb-gen-back-rank-5",
    fen: "5q2/8/8/7K/8/R7/1nQ5/7k w - - 0 1",
    orientation: "white",
    solution: ["a3a1", "b2d1", "a1d1", "f8f1", "d1f1"],
    goal: { type: "mate", inMoves: 3 },
    theme: "back-rank",
    difficulty: 3,
    prompt: "White to play and force mate in three.",
  },
  {
    id: "tb-gen-back-rank-6",
    fen: "1k2b3/8/2R4r/8/8/5K2/8/6Q1 w - - 0 1",
    orientation: "white",
    solution: ["g1b6", "b8a8", "c6c8"],
    goal: { type: "mate", inMoves: 2 },
    theme: "back-rank",
    difficulty: 2,
    prompt: "White to play and force mate in two.",
  },
  {
    id: "tb-gen-win-material-33",
    fen: "8/8/6p1/8/2P2K2/N2N2r1/4k3/8 w - - 0 1",
    orientation: "white",
    solution: ["f4g3"],
    goal: { type: "win-material", minGain: 5 },
    theme: "win-material",
    difficulty: 1,
    prompt: "White to play and win material.",
  },
  {
    id: "tb-gen-mate-16",
    fen: "1K6/8/k6p/8/8/8/PB2q1Q1/8 w - - 0 1",
    orientation: "white",
    solution: ["g2c6", "a6a5", "b2c3"],
    goal: { type: "mate", inMoves: 2 },
    theme: "mate",
    difficulty: 2,
    prompt: "White to play and force mate in two.",
  },
  {
    id: "tb-gen-win-material-34",
    fen: "3b4/8/1n4p1/Q7/7p/1k6/8/4K3 w - - 0 1",
    orientation: "white",
    solution: ["a5b5"],
    goal: { type: "win-material", minGain: 3 },
    theme: "win-material",
    difficulty: 2,
    prompt: "White to play and win material.",
  },
  {
    id: "tb-gen-mate-17",
    fen: "7q/8/6Q1/k1P5/8/P4p2/1p6/4K3 w - - 0 1",
    orientation: "white",
    solution: ["g6b6", "a5a4", "b6b4"],
    goal: { type: "mate", inMoves: 2 },
    theme: "mate",
    difficulty: 2,
    prompt: "White to play and force mate in two.",
  },
  {
    id: "tb-gen-win-material-35",
    fen: "8/b2p4/8/1R6/8/k7/8/1K6 w - - 0 1",
    orientation: "white",
    solution: ["b5a5"],
    goal: { type: "win-material", minGain: 3 },
    theme: "win-material",
    difficulty: 2,
    prompt: "White to play and win material.",
  },
  {
    id: "tb-gen-mate-18",
    fen: "8/8/2p5/k1K5/8/1P6/1R6/5B2 w - - 0 1",
    orientation: "white",
    solution: ["b2a2"],
    goal: { type: "mate", inMoves: 1 },
    theme: "mate",
    difficulty: 1,
    prompt: "White to play and mate in one.",
  },
  {
    id: "tb-gen-mate-19",
    fen: "8/6P1/7k/3K4/8/2R5/8/5N2 w - - 0 1",
    orientation: "white",
    solution: ["g7g8q", "h6h5", "c3h3"],
    goal: { type: "mate", inMoves: 2 },
    theme: "mate",
    difficulty: 2,
    prompt: "White to play and force mate in two.",
  },
  {
    id: "tb-gen-mate-20",
    fen: "3b4/1Q6/3p3p/6R1/2k5/5r2/1K6/8 w - - 0 1",
    orientation: "white",
    solution: ["b7e4"],
    goal: { type: "mate", inMoves: 1 },
    theme: "mate",
    difficulty: 1,
    prompt: "White to play and mate in one.",
  },
  {
    id: "tb-gen-mate-21",
    fen: "5r2/4k3/7Q/B4P2/7p/2K4P/8/8 w - - 0 1",
    orientation: "white",
    solution: ["h6e6"],
    goal: { type: "mate", inMoves: 1 },
    theme: "mate",
    difficulty: 1,
    prompt: "White to play and mate in one.",
  },
  {
    id: "tb-gen-mate-22",
    fen: "8/4n3/RQ6/1K6/1P6/6P1/8/5k2 w - - 0 1",
    orientation: "white",
    solution: ["a6a2", "e7g6", "b6f2"],
    goal: { type: "mate", inMoves: 2 },
    theme: "mate",
    difficulty: 2,
    prompt: "White to play and force mate in two.",
  },
  {
    id: "tb-gen-mate-23",
    fen: "7r/8/8/8/8/1K6/7Q/2k5 w - - 0 1",
    orientation: "white",
    solution: ["h2c2"],
    goal: { type: "mate", inMoves: 1 },
    theme: "mate",
    difficulty: 1,
    prompt: "White to play and mate in one.",
  },
  {
    id: "tb-gen-win-material-36",
    fen: "3N4/2K3P1/2P4k/8/n7/8/8/3r3N w - - 0 1",
    orientation: "white",
    solution: ["g7g8q"],
    goal: { type: "win-material", minGain: 5 },
    theme: "win-material",
    difficulty: 2,
    prompt: "White to play and win material.",
  },
  {
    id: "tb-gen-win-material-37",
    fen: "b7/R7/1K6/N7/k2r4/8/8/8 w - - 0 1",
    orientation: "white",
    solution: ["a5c6"],
    goal: { type: "win-material", minGain: 3 },
    theme: "win-material",
    difficulty: 2,
    prompt: "White to play and win material.",
  },
  {
    id: "tb-gen-mate-24",
    fen: "2Q5/5K2/8/4k3/8/7P/1p2N3/8 w - - 0 1",
    orientation: "white",
    solution: ["c8e6"],
    goal: { type: "mate", inMoves: 1 },
    theme: "mate",
    difficulty: 1,
    prompt: "White to play and mate in one.",
  },
  {
    id: "tb-gen-win-material-38",
    fen: "8/3P4/2p5/7P/1Q1K4/8/2k5/r6r w - - 0 1",
    orientation: "white",
    solution: ["b4c3"],
    goal: { type: "win-material", minGain: 5 },
    theme: "win-material",
    difficulty: 2,
    prompt: "White to play and win material.",
  },
  {
    id: "tb-gen-win-material-39",
    fen: "3r4/1N6/8/8/6K1/5R1p/1k6/6n1 w - - 0 1",
    orientation: "white",
    solution: ["f3f2"],
    goal: { type: "win-material", minGain: 2 },
    theme: "win-material",
    difficulty: 2,
    prompt: "White to play and win material.",
  },
  {
    id: "tb-gen-win-material-40",
    fen: "6r1/3n4/1B2P3/1k1K4/8/4R3/8/8 w - - 0 1",
    orientation: "white",
    solution: ["e6d7"],
    goal: { type: "win-material", minGain: 5 },
    theme: "win-material",
    difficulty: 1,
    prompt: "White to play and win material.",
  },
  {
    id: "tb-gen-back-rank-7",
    fen: "5K2/8/R7/8/8/4q3/5Q2/2k5 w - - 0 1",
    orientation: "white",
    solution: ["a6a1"],
    goal: { type: "mate", inMoves: 1 },
    theme: "back-rank",
    difficulty: 1,
    prompt: "White to play and mate in one.",
  },
  {
    id: "tb-gen-mate-25",
    fen: "8/7P/8/4n2r/3P4/7p/2K1Q3/k7 w - - 0 1",
    orientation: "white",
    solution: ["e2a6"],
    goal: { type: "mate", inMoves: 1 },
    theme: "mate",
    difficulty: 1,
    prompt: "White to play and mate in one.",
  },
  {
    id: "tb-gen-mate-26",
    fen: "8/8/8/2P5/6b1/8/k1K4B/4Qq2 w - - 0 1",
    orientation: "white",
    solution: ["e1a5"],
    goal: { type: "mate", inMoves: 1 },
    theme: "mate",
    difficulty: 1,
    prompt: "White to play and mate in one.",
  },
  {
    id: "tb-gen-win-material-41",
    fen: "3r4/2r4p/8/8/6P1/1RR5/6k1/K7 w - - 0 1",
    orientation: "white",
    solution: ["b3b2"],
    goal: { type: "win-material", minGain: 5 },
    theme: "win-material",
    difficulty: 2,
    prompt: "White to play and win material.",
  },
  {
    id: "tb-gen-win-material-42",
    fen: "8/4r1p1/8/1k1N4/8/8/1K1b3R/8 w - - 0 1",
    orientation: "white",
    solution: ["d5e7"],
    goal: { type: "win-material", minGain: 2 },
    theme: "win-material",
    difficulty: 1,
    prompt: "White to play and win material.",
  },
  {
    id: "tb-gen-win-material-43",
    fen: "8/1K5k/4PB2/4b3/3P4/8/8/6n1 w - - 0 1",
    orientation: "white",
    solution: ["d4e5"],
    goal: { type: "win-material", minGain: 5 },
    theme: "win-material",
    difficulty: 1,
    prompt: "White to play and win material.",
  },
  {
    id: "tb-gen-back-rank-8",
    fen: "4k3/8/4K3/8/6N1/8/8/5R2 w - - 0 1",
    orientation: "white",
    solution: ["e6d6", "e8d8", "f1f8"],
    goal: { type: "mate", inMoves: 2 },
    theme: "back-rank",
    difficulty: 2,
    prompt: "White to play and force mate in two.",
  },
  {
    id: "tb-gen-win-material-44",
    fen: "8/6K1/8/r2n4/3PQ3/p1k5/8/8 w - - 0 1",
    orientation: "white",
    solution: ["e4e1"],
    goal: { type: "win-material", minGain: 2 },
    theme: "win-material",
    difficulty: 2,
    prompt: "White to play and win material.",
  },
  {
    id: "tb-gen-mate-27",
    fen: "K7/2k4n/3R4/3p4/8/R7/8/8 w - - 0 1",
    orientation: "white",
    solution: ["a3a6", "h7g5", "a6c6"],
    goal: { type: "mate", inMoves: 2 },
    theme: "mate",
    difficulty: 2,
    prompt: "White to play and force mate in two.",
  },
  {
    id: "tb-gen-win-material-45",
    fen: "2b4R/8/8/5k2/5q2/p5Q1/6pK/8 w - - 0 1",
    orientation: "white",
    solution: ["h8f8"],
    goal: { type: "win-material", minGain: 5 },
    theme: "win-material",
    difficulty: 2,
    prompt: "White to play and win material.",
  },
  {
    id: "tb-gen-win-material-46",
    fen: "8/P2K4/p7/8/2k5/2r5/3Q3P/6r1 w - - 0 1",
    orientation: "white",
    solution: ["a7a8q"],
    goal: { type: "win-material", minGain: 5 },
    theme: "win-material",
    difficulty: 2,
    prompt: "White to play and win material.",
  },
  {
    id: "tb-gen-win-material-47",
    fen: "3N4/k6K/8/1q6/1Q6/1b6/8/8 w - - 0 1",
    orientation: "white",
    solution: ["b4b5"],
    goal: { type: "win-material", minGain: 5 },
    theme: "win-material",
    difficulty: 1,
    prompt: "White to play and win material.",
  },
  {
    id: "tb-gen-win-material-48",
    fen: "6k1/1nb5/P7/8/8/8/5p1N/N1K5 w - - 0 1",
    orientation: "white",
    solution: ["a6a7"],
    goal: { type: "win-material", minGain: 3 },
    theme: "win-material",
    difficulty: 2,
    prompt: "White to play and win material.",
  },
  {
    id: "tb-gen-mate-28",
    fen: "1R5Q/8/8/7P/8/k7/8/1K2n3 w - - 0 1",
    orientation: "white",
    solution: ["h8a1"],
    goal: { type: "mate", inMoves: 1 },
    theme: "mate",
    difficulty: 1,
    prompt: "White to play and mate in one.",
  },
  {
    id: "tb-gen-back-rank-9",
    fen: "2k5/4P3/1Q3K2/r7/6N1/8/8/8 w - - 0 1",
    orientation: "white",
    solution: ["e7e8q"],
    goal: { type: "mate", inMoves: 1 },
    theme: "back-rank",
    difficulty: 1,
    prompt: "White to play and mate in one.",
  },
  {
    id: "tb-gen-back-rank-10",
    fen: "8/8/6p1/8/RK6/4Q3/7p/1k6 w - - 0 1",
    orientation: "white",
    solution: ["e3c3", "h2h1q", "a4a1"],
    goal: { type: "mate", inMoves: 2 },
    theme: "back-rank",
    difficulty: 2,
    prompt: "White to play and force mate in two.",
  },
  {
    id: "tb-gen-win-material-49",
    fen: "8/3r4/2B5/8/8/8/3P3k/4K3 w - - 0 1",
    orientation: "white",
    solution: ["c6d7"],
    goal: { type: "win-material", minGain: 5 },
    theme: "win-material",
    difficulty: 1,
    prompt: "White to play and win material.",
  },
  {
    id: "tb-gen-win-material-50",
    fen: "8/8/3p4/2k4P/b7/8/1p4K1/3R4 w - - 0 1",
    orientation: "white",
    solution: ["d1b1"],
    goal: { type: "win-material", minGain: 2 },
    theme: "win-material",
    difficulty: 2,
    prompt: "White to play and win material.",
  },
  {
    id: "tb-gen-mate-29",
    fen: "8/7p/3K4/8/n7/1Q6/8/k1N5 w - - 0 1",
    orientation: "white",
    solution: ["b3a2"],
    goal: { type: "mate", inMoves: 1 },
    theme: "mate",
    difficulty: 1,
    prompt: "White to play and mate in one.",
  },
  {
    id: "tb-gen-win-material-51",
    fen: "8/8/4k3/8/8/7p/7R/5bK1 w - - 0 1",
    orientation: "white",
    solution: ["g1f1"],
    goal: { type: "win-material", minGain: 2 },
    theme: "win-material",
    difficulty: 1,
    prompt: "White to play and win material.",
  },
  {
    id: "tb-gen-win-material-52",
    fen: "8/2K1p1k1/8/3PR3/8/8/3r4/8 w - - 0 1",
    orientation: "white",
    solution: ["e5e7"],
    goal: { type: "win-material", minGain: 2 },
    theme: "win-material",
    difficulty: 1,
    prompt: "White to play and win material.",
  },
  {
    id: "tb-gen-win-material-53",
    fen: "5k2/4N3/P7/4n3/8/7p/3K1p1P/8 w - - 0 1",
    orientation: "white",
    solution: ["d2e2"],
    goal: { type: "win-material", minGain: 3 },
    theme: "win-material",
    difficulty: 2,
    prompt: "White to play and win material.",
  },
  {
    id: "tb-gen-mate-30",
    fen: "2k5/8/1r1Q4/2K5/5P2/4R3/8/3r4 w - - 0 1",
    orientation: "white",
    solution: ["e3e8", "c8b7", "d6b6"],
    goal: { type: "mate", inMoves: 2 },
    theme: "mate",
    difficulty: 2,
    prompt: "White to play and force mate in two.",
  },
  {
    id: "tb-gen-mate-31",
    fen: "6k1/8/4PK2/8/n7/1Q6/q1p5/8 w - - 0 1",
    orientation: "white",
    solution: ["b3g3", "g8h8", "g3g7"],
    goal: { type: "mate", inMoves: 2 },
    theme: "mate",
    difficulty: 2,
    prompt: "White to play and force mate in two.",
  },
  {
    id: "tb-gen-win-material-54",
    fen: "3k4/2p2n2/8/5B2/3K4/8/8/r5R1 w - - 0 1",
    orientation: "white",
    solution: ["g1a1"],
    goal: { type: "win-material", minGain: 2 },
    theme: "win-material",
    difficulty: 1,
    prompt: "White to play and win material.",
  },
  {
    id: "tb-gen-mate-32",
    fen: "3k4/N4P2/Q2p2K1/8/8/8/8/8 w - - 0 1",
    orientation: "white",
    solution: ["a6d6"],
    goal: { type: "mate", inMoves: 1 },
    theme: "mate",
    difficulty: 1,
    prompt: "White to play and mate in one.",
  },
  {
    id: "tb-gen-mate-33",
    fen: "1K6/1n6/1P3R2/5PR1/8/7k/8/7b w - - 0 1",
    orientation: "white",
    solution: ["f6h6"],
    goal: { type: "mate", inMoves: 1 },
    theme: "mate",
    difficulty: 1,
    prompt: "White to play and mate in one.",
  },
  {
    id: "tb-gen-win-material-55",
    fen: "8/6p1/1P2K3/1P6/3R4/3n1k2/1b6/8 w - - 0 1",
    orientation: "white",
    solution: ["d4d3"],
    goal: { type: "win-material", minGain: 5 },
    theme: "win-material",
    difficulty: 1,
    prompt: "White to play and win material.",
  },
  {
    id: "tb-gen-mate-34",
    fen: "8/8/2K5/k7/6R1/2N2n2/8/8 w - - 0 1",
    orientation: "white",
    solution: ["g4a4"],
    goal: { type: "mate", inMoves: 1 },
    theme: "mate",
    difficulty: 1,
    prompt: "White to play and mate in one.",
  },
  {
    id: "tb-gen-mate-35",
    fen: "7Q/1k1K4/4pb2/5R2/5r2/8/1p6/8 w - - 0 1",
    orientation: "white",
    solution: ["h8c8", "b7b6", "c8c7", "b6a6", "f5a5"],
    goal: { type: "mate", inMoves: 3 },
    theme: "mate",
    difficulty: 3,
    prompt: "White to play and force mate in three.",
  },
  {
    id: "tb-gen-mate-36",
    fen: "Q7/6k1/1P1K4/8/8/8/6p1/3R1r2 w - - 0 1",
    orientation: "white",
    solution: ["a8g2", "g7h6", "d1f1", "h6h7", "f1h1"],
    goal: { type: "mate", inMoves: 3 },
    theme: "mate",
    difficulty: 3,
    prompt: "White to play and force mate in three.",
  },
  {
    id: "tb-gen-mate-37",
    fen: "4k3/8/3B1Q2/8/8/1bK5/8/8 w - - 0 1",
    orientation: "white",
    solution: ["f6e7"],
    goal: { type: "mate", inMoves: 1 },
    theme: "mate",
    difficulty: 1,
    prompt: "White to play and mate in one.",
  },
  {
    id: "tb-gen-mate-38",
    fen: "8/6P1/8/1K3P2/p7/8/1R5N/6k1 w - - 0 1",
    orientation: "white",
    solution: ["g7g8q", "g1h1", "g8g2"],
    goal: { type: "mate", inMoves: 2 },
    theme: "mate",
    difficulty: 2,
    prompt: "White to play and force mate in two.",
  },
  {
    id: "tb-gen-mate-39",
    fen: "2n5/4n3/7Q/2P5/8/6k1/4K1Np/8 w - - 0 1",
    orientation: "white",
    solution: ["h6g5", "g3h3", "g2f4"],
    goal: { type: "mate", inMoves: 2 },
    theme: "mate",
    difficulty: 2,
    prompt: "White to play and force mate in two.",
  },
  {
    id: "tb-gen-mate-40",
    fen: "8/1R6/P5k1/8/8/5KP1/8/5R2 w - - 0 1",
    orientation: "white",
    solution: ["f3g4", "g6h6", "f1f6"],
    goal: { type: "mate", inMoves: 2 },
    theme: "mate",
    difficulty: 2,
    prompt: "White to play and force mate in two.",
  },
  {
    id: "tb-gen-mate-41",
    fen: "2n4k/8/1p6/6Q1/6P1/1K6/5R2/3n4 w - - 0 1",
    orientation: "white",
    solution: ["f2h2"],
    goal: { type: "mate", inMoves: 1 },
    theme: "mate",
    difficulty: 1,
    prompt: "White to play and mate in one.",
  },
  {
    id: "tb-gen-mate-42",
    fen: "4n3/1P4R1/2Q4b/7k/8/8/8/1K6 w - - 0 1",
    orientation: "white",
    solution: ["c6h1"],
    goal: { type: "mate", inMoves: 1 },
    theme: "mate",
    difficulty: 1,
    prompt: "White to play and mate in one.",
  },
  {
    id: "tb-gen-back-rank-11",
    fen: "1Q6/8/8/3n4/8/7K/2B3p1/kn6 w - - 0 1",
    orientation: "white",
    solution: ["b8b1"],
    goal: { type: "mate", inMoves: 1 },
    theme: "back-rank",
    difficulty: 1,
    prompt: "White to play and mate in one.",
  },
  {
    id: "tb-gen-mate-43",
    fen: "5r2/8/8/8/8/6KR/n2Q4/6k1 w - - 0 1",
    orientation: "white",
    solution: ["d2g2"],
    goal: { type: "mate", inMoves: 1 },
    theme: "mate",
    difficulty: 1,
    prompt: "White to play and mate in one.",
  },
  {
    id: "tb-gen-mate-44",
    fen: "8/2P5/8/K7/6r1/4Q3/8/1N1k4 w - - 0 1",
    orientation: "white",
    solution: ["e3d2"],
    goal: { type: "mate", inMoves: 1 },
    theme: "mate",
    difficulty: 1,
    prompt: "White to play and mate in one.",
  },
  {
    id: "tb-gen-back-rank-12",
    fen: "1k6/p4B2/1bK5/7Q/8/8/3n4/8 w - - 0 1",
    orientation: "white",
    solution: ["h5h8", "b6d8", "h8d8"],
    goal: { type: "mate", inMoves: 2 },
    theme: "back-rank",
    difficulty: 2,
    prompt: "White to play and force mate in two.",
  },
  {
    id: "tb-gen-mate-45",
    fen: "8/b6P/8/N7/7p/K2P4/8/k7 w - - 0 1",
    orientation: "white",
    solution: ["h7h8q", "a7d4", "h8d4", "a1b1", "d4b2"],
    goal: { type: "mate", inMoves: 3 },
    theme: "mate",
    difficulty: 3,
    prompt: "White to play and force mate in three.",
  },
  {
    id: "tb-gen-mate-46",
    fen: "8/5p1B/3P4/8/3P4/1RK5/8/k7 w - - 0 1",
    orientation: "white",
    solution: ["b3a3"],
    goal: { type: "mate", inMoves: 1 },
    theme: "mate",
    difficulty: 1,
    prompt: "White to play and mate in one.",
  },
  {
    id: "tb-gen-mate-47",
    fen: "2r5/7p/4r1R1/8/5P1k/8/4Q2K/8 w - - 0 1",
    orientation: "white",
    solution: ["e2g4"],
    goal: { type: "mate", inMoves: 1 },
    theme: "mate",
    difficulty: 1,
    prompt: "White to play and mate in one.",
  },
  {
    id: "tb-gen-mate-48",
    fen: "8/2K1b1P1/8/3k4/8/2Qp4/8/8 w - - 0 1",
    orientation: "white",
    solution: ["g7g8q", "d5e4", "g8g4", "e4e3", "c3e1"],
    goal: { type: "mate", inMoves: 3 },
    theme: "mate",
    difficulty: 3,
    prompt: "White to play and force mate in three.",
  },
  {
    id: "tb-gen-mate-49",
    fen: "8/q7/k3K1Q1/8/8/1R6/8/8 w - - 0 1",
    orientation: "white",
    solution: ["g6d3", "a6a5", "d3b5"],
    goal: { type: "mate", inMoves: 2 },
    theme: "mate",
    difficulty: 2,
    prompt: "White to play and force mate in two.",
  },
  {
    id: "tb-gen-mate-50",
    fen: "8/1Q5r/2K5/8/k7/1nP5/8/8 w - - 0 1",
    orientation: "white",
    solution: ["b7b4"],
    goal: { type: "mate", inMoves: 1 },
    theme: "mate",
    difficulty: 1,
    prompt: "White to play and mate in one.",
  },
  {
    id: "tb-gen-mate-51",
    fen: "8/8/K7/P7/3P4/6pk/B2Q3q/8 w - - 0 1",
    orientation: "white",
    solution: ["a2e6", "h3h4", "d2h6"],
    goal: { type: "mate", inMoves: 2 },
    theme: "mate",
    difficulty: 2,
    prompt: "White to play and force mate in two.",
  },
  {
    id: "tb-gen-mate-52",
    fen: "4K3/7R/k7/2Q4p/8/2n5/7b/8 w - - 0 1",
    orientation: "white",
    solution: ["h7a7"],
    goal: { type: "mate", inMoves: 1 },
    theme: "mate",
    difficulty: 1,
    prompt: "White to play and mate in one.",
  },
  {
    id: "tb-gen-back-rank-13",
    fen: "6r1/8/2R3P1/4p3/7p/5K1R/8/6k1 w - - 0 1",
    orientation: "white",
    solution: ["c6c1"],
    goal: { type: "mate", inMoves: 1 },
    theme: "back-rank",
    difficulty: 1,
    prompt: "White to play and mate in one.",
  },
  {
    id: "tb-gen-back-rank-14",
    fen: "6K1/3p3R/3b4/8/1nP5/8/2R5/5k2 w - - 0 1",
    orientation: "white",
    solution: ["h7h1"],
    goal: { type: "mate", inMoves: 1 },
    theme: "back-rank",
    difficulty: 1,
    prompt: "White to play and mate in one.",
  },
  {
    id: "tb-gen-mate-53",
    fen: "5k2/6b1/K5P1/8/1RQ5/8/P5p1/8 w - - 0 1",
    orientation: "white",
    solution: ["c4f7"],
    goal: { type: "mate", inMoves: 1 },
    theme: "mate",
    difficulty: 1,
    prompt: "White to play and mate in one.",
  },
  {
    id: "tb-gen-mate-54",
    fen: "7n/4R3/5K2/8/7k/8/5p2/3Q4 w - - 0 1",
    orientation: "white",
    solution: ["d1f3", "h8f7", "e7e4"],
    goal: { type: "mate", inMoves: 2 },
    theme: "mate",
    difficulty: 2,
    prompt: "White to play and force mate in two.",
  },
  {
    id: "tb-gen-mate-55",
    fen: "3R4/1n1K4/8/k7/2p5/P4Q2/8/2q5 w - - 0 1",
    orientation: "white",
    solution: ["d8a8", "a5b6", "f3c6"],
    goal: { type: "mate", inMoves: 2 },
    theme: "mate",
    difficulty: 2,
    prompt: "White to play and force mate in two.",
  },
  {
    id: "tb-gen-back-rank-15",
    fen: "8/8/8/4K3/p4R2/1RP5/1b4P1/4k3 w - - 0 1",
    orientation: "white",
    solution: ["b3b2", "a4a3", "b2a2", "e1d1", "f4f1"],
    goal: { type: "mate", inMoves: 3 },
    theme: "back-rank",
    difficulty: 3,
    prompt: "White to play and force mate in three.",
  },
  {
    id: "tb-gen-back-rank-16",
    fen: "8/1K1P4/8/1P6/8/3R4/2R5/6k1 w - - 0 1",
    orientation: "white",
    solution: ["d3d1"],
    goal: { type: "mate", inMoves: 1 },
    theme: "back-rank",
    difficulty: 1,
    prompt: "White to play and mate in one.",
  },
  {
    id: "tb-gen-fork-2",
    fen: "6k1/8/6N1/5r2/3P3K/1P6/8/8 w - - 0 1",
    orientation: "white",
    solution: ["g6e7"],
    goal: { type: "win-material", minGain: 5 },
    theme: "fork",
    difficulty: 2,
    prompt: "White to play — a knight fork wins material.",
  },
  {
    id: "tb-gen-back-rank-17",
    fen: "k7/4b3/2p1p3/8/2K2Q2/6B1/8/8 w - - 0 1",
    orientation: "white",
    solution: ["f4b8"],
    goal: { type: "mate", inMoves: 1 },
    theme: "back-rank",
    difficulty: 1,
    prompt: "White to play and mate in one.",
  },
  {
    id: "tb-gen-back-rank-18",
    fen: "2Nk4/8/1K6/8/8/n1P2Q2/7b/8 w - - 0 1",
    orientation: "white",
    solution: ["f3f8", "d8d7", "f8e7", "d7c8", "e7e8"],
    goal: { type: "mate", inMoves: 3 },
    theme: "back-rank",
    difficulty: 3,
    prompt: "White to play and force mate in three.",
  },
  {
    id: "tb-gen-back-rank-19",
    fen: "1k6/6pR/1K6/p7/4n3/2n4N/8/8 w - - 0 1",
    orientation: "white",
    solution: ["h7h8"],
    goal: { type: "mate", inMoves: 1 },
    theme: "back-rank",
    difficulty: 1,
    prompt: "White to play and mate in one.",
  },
  {
    id: "tb-gen-back-rank-20",
    fen: "6R1/b7/8/8/5R2/2K5/8/2k5 w - - 0 1",
    orientation: "white",
    solution: ["f4f1"],
    goal: { type: "mate", inMoves: 1 },
    theme: "back-rank",
    difficulty: 1,
    prompt: "White to play and mate in one.",
  },
  {
    id: "tb-gen-fork-3",
    fen: "3r4/N1p1k3/8/8/2Rb2K1/3P4/8/8 w - - 0 1",
    orientation: "white",
    solution: ["a7c6"],
    goal: { type: "win-material", minGain: 3 },
    theme: "fork",
    difficulty: 2,
    prompt: "White to play — a knight fork wins material.",
  },
  {
    id: "tb-gen-fork-4",
    fen: "8/2k5/K2p4/8/6P1/b1NP4/8/8 w - - 0 1",
    orientation: "white",
    solution: ["c3b5"],
    goal: { type: "win-material", minGain: 5 },
    theme: "fork",
    difficulty: 2,
    prompt: "White to play — a knight fork wins material.",
  },
  {
    id: "tb-gen-back-rank-21",
    fen: "8/8/K7/n3R3/5P2/n4p2/5R2/1k6 w - - 0 1",
    orientation: "white",
    solution: ["e5e1"],
    goal: { type: "mate", inMoves: 1 },
    theme: "back-rank",
    difficulty: 1,
    prompt: "White to play and mate in one.",
  },
  {
    id: "tb-gen-back-rank-22",
    fen: "8/1b5R/8/8/3r4/p1P4K/2R5/7k w - - 0 1",
    orientation: "white",
    solution: ["c2c1", "d4d1", "c1d1"],
    goal: { type: "mate", inMoves: 2 },
    theme: "back-rank",
    difficulty: 2,
    prompt: "White to play and force mate in two.",
  },
  {
    id: "tb-gen-back-rank-23",
    fen: "1k6/4N3/1K6/8/8/8/3Q4/3b4 w - - 0 1",
    orientation: "white",
    solution: ["d2d8"],
    goal: { type: "mate", inMoves: 1 },
    theme: "back-rank",
    difficulty: 1,
    prompt: "White to play and mate in one.",
  },
  {
    id: "tb-gen-back-rank-24",
    fen: "6k1/8/6K1/R1p5/8/3B4/8/8 w - - 0 1",
    orientation: "white",
    solution: ["a5a8"],
    goal: { type: "mate", inMoves: 1 },
    theme: "back-rank",
    difficulty: 1,
    prompt: "White to play and mate in one.",
  },
  {
    id: "tb-gen-back-rank-25",
    fen: "R6R/2p2P2/4n3/8/1p6/8/8/K1k5 w - - 0 1",
    orientation: "white",
    solution: ["a8a2", "b4b3", "h8h1"],
    goal: { type: "mate", inMoves: 2 },
    theme: "back-rank",
    difficulty: 2,
    prompt: "White to play and force mate in two.",
  },
  {
    id: "tb-gen-back-rank-26",
    fen: "5k2/1Q4b1/P7/8/8/8/3R4/3K3n w - - 0 1",
    orientation: "white",
    solution: ["d2d8"],
    goal: { type: "mate", inMoves: 1 },
    theme: "back-rank",
    difficulty: 1,
    prompt: "White to play and mate in one.",
  },
  {
    id: "tb-gen-back-rank-27",
    fen: "1k2K3/b1R5/5p2/8/6Q1/8/r7/8 w - - 0 1",
    orientation: "white",
    solution: ["g4c8"],
    goal: { type: "mate", inMoves: 1 },
    theme: "back-rank",
    difficulty: 1,
    prompt: "White to play and mate in one.",
  },
  {
    id: "tb-gen-fork-5",
    fen: "8/1k6/N3q3/8/6P1/1P2N1K1/8/8 w - - 0 1",
    orientation: "white",
    solution: ["a6c5"],
    goal: { type: "win-material", minGain: 5 },
    theme: "fork",
    difficulty: 2,
    prompt: "White to play — a knight fork wins material.",
  },
  {
    id: "tb-gen-back-rank-28",
    fen: "7k/7r/5P1p/8/8/5N2/2Q5/2K5 w - - 0 1",
    orientation: "white",
    solution: ["c2c8"],
    goal: { type: "mate", inMoves: 1 },
    theme: "back-rank",
    difficulty: 1,
    prompt: "White to play and mate in one.",
  },
  {
    id: "tb-gen-back-rank-29",
    fen: "2k5/8/3KR3/P1n5/3Pr1Q1/8/8/8 w - - 0 1",
    orientation: "white",
    solution: ["e6e8", "c8b7", "g4c8", "b7a7", "c8a8"],
    goal: { type: "mate", inMoves: 3 },
    theme: "back-rank",
    difficulty: 3,
    prompt: "White to play and force mate in three.",
  },
  {
    id: "tb-gen-back-rank-30",
    fen: "8/3R2r1/7p/2b2R2/2K5/8/8/k7 w - - 0 1",
    orientation: "white",
    solution: ["f5f1", "a1a2", "d7d2", "a2a3", "f1a1"],
    goal: { type: "mate", inMoves: 3 },
    theme: "back-rank",
    difficulty: 3,
    prompt: "White to play and force mate in three.",
  },];
