// AUTO-GENERATED by scripts/scene-art/generate-portraits.ts — do not edit by hand.
// Painted character headshots (public/images/characters/<id>.*) and Pip mascot poses
// (public/images/mascot/pip-<mood>.*). Empty entries fall back to inline SVG.
export const CHARACTER_IMAGES: Record<string, string> = {
  "aurora": "aurora.webp",
  "belle": "belle.webp",
  "caller": "caller.webp",
  "cedric": "cedric.webp",
  "murk": "murk.webp",
  "nim": "nim.webp",
  "pip": "pip.webp",
  "rookwell": "rookwell.webp",
};

export const PIP_MASCOT_IMAGES: Record<string, string> = {
  "cheer": "pip-cheer.webp",
  "idle": "pip-idle.webp",
  "think": "pip-think.webp",
};
