// AUTO-GENERATED by scripts/scene-art/generate-scenes.ts — do not edit by hand.
// Maps a story scene id (SceneActivity.id, e.g. "kids-l1-board-hook") to its
// bespoke illustration filename under public/images/scenes/. Empty until
// `npm run art:generate` has rendered images; while a scene has no entry, SceneArt
// falls back to its inline-SVG backdrop (so the app always renders).
export const SCENE_IMAGES: Record<string, string> = {};
