// AUTO-GENERATED by scripts/tts/generate-audio.ts — do not edit by hand.
// Maps a dialogue clip key (see dialogueKey.ts) to its audio filename under
// public/audio/dialogue/. Empty until `npm run tts:generate` has rendered clips;
// while empty, speakAs() falls back to the Web Speech voice for every line.
export const CLIP_FILES: Record<string, string> = {};
