// "Annotated Master Games" module — full classic games walked move by move with
// a live Stockfish eval bar, so the learner watches strategy and attack unfold
// from the opening to the finish, not just an opening fragment.
//
// The GAME MOVES are historical facts (public domain); all annotations are
// original. Every game line is legality-checked by `npm run validate`; the Opera
// finish puzzle is engine-verified (sound + unique).

import type { Lesson, Module } from "../../types";

const overview: Lesson = {
  id: "mg-overview",
  title: "How to study a master game",
  summary: "Watching a great game teaches more than a hundred rules — if you watch it the right way.",
  activities: [
    {
      type: "concept",
      id: "mg-overview-concept",
      title: "Watch with questions",
      blurb: "Don't just replay — interrogate.",
      body:
        "A master game is a whole story: an opening plan, a middlegame fight, and a decisive finish. Replaying one passively teaches little. The trick is to watch with questions — before each move, ask 'what would I play, and why?', then see what the master chose and how it differs.\n\nKeep an eye on the eval bar as you step through. It shows you exactly when the balance shifted — the moment one side's plan triumphed or a mistake was punished. Find that turning point and you've found the lesson. These three classics are the most replayed games in history; learn them and you'll carry their ideas into your own play.",
      points: [
        "A game = opening plan → middlegame fight → finish. Watch the whole arc.",
        "Before each move, guess it — then compare with the master's choice.",
        "The eval bar reveals the turning point: where the game was decided.",
      ],
    },
  ],
};

const opera: Lesson = {
  id: "mg-opera",
  title: "Morphy's Opera Game",
  summary: "Paul Morphy, 1858 — a flawless demonstration of development, open lines, and a finishing sacrifice.",
  activities: [
    {
      type: "concept",
      id: "mg-opera-concept",
      title: "The model attacking game",
      blurb: "Develop, open lines, sacrifice, mate.",
      body:
        "Paul Morphy played this at the Paris Opera in 1858 against two amateurs consulting together. It's the most famous teaching game ever played: every white move develops a piece or opens a line, Morphy never wastes a tempo, and the whole thing ends in a clean sacrificial mate.\n\nWatch how a lead in development — pieces out fast, lines opened — converts directly into a winning attack. This is opening principles turned into a knockout.",
      points: [
        "Develop every piece toward the centre; don't move the same piece twice.",
        "Open lines feed an attack; a lead in development is meant to be used.",
        "When the pieces are all aimed at the king, look for the sacrifice.",
      ],
    },
    {
      type: "replay",
      id: "mg-opera-game",
      title: "The Opera Game, move by move",
      blurb: "Morphy vs the Allies, Paris 1858.",
      orientation: "white",
      eval: true,
      source: "Morphy vs Duke of Brunswick & Count Isouard, Paris 1858",
      intro:
        "White: Paul Morphy. A masterclass in development and open lines. Step through and watch every piece join the attack — and the eval bar tilt steadily to White.",
      steps: [
        { san: "e4", note: "Claim the centre and open lines for the bishop and queen." },
        { san: "e5", note: "Black answers in the centre." },
        { san: "Nf3", note: "Develop with a threat to e5." },
        { san: "d6", note: "The Philidor — solid but passive; it shuts in Black's own bishop." },
        { san: "d4", note: "Strike at the centre immediately." },
        { san: "Bg4", note: "Pinning the knight — but this bishop will soon be traded, helping White develop." },
        { san: "dxe5", note: "Opening the position while Black's king is still in the centre." },
        { san: "Bxf3", note: "Black gives up the bishop to avoid losing a pawn." },
        { san: "Qxf3", keyIdea: "Develop, don't recapture passively", note: "Recapturing with the queen — already eyeing f7 and developing toward the attack." },
        { san: "dxe5", note: "Black regains the pawn, but White is far ahead in development." },
        { san: "Bc4", keyIdea: "Aim at f7", note: "The bishop joins the queen against f7 — Black's weakest square, defended only by the king." },
        { san: "Nf6", note: "Black develops and defends, but the king is still stuck in the centre." },
        { san: "Qb3", note: "Doubling on the f7-diagonal AND hitting b7 — two threats at once." },
        { san: "Qe7", note: "Black must defend f7 awkwardly with the queen, blocking the bishop." },
        { san: "Nc3", keyIdea: "Develop everything — even for free", note: "Morphy declines to grab b7 with the queen; instead he brings the LAST piece into play. Development over a pawn." },
        { san: "c6", note: "Black covers d5/b5 and tries to untangle." },
        { san: "Bg5", note: "The final minor piece develops, pinning the f6-knight. Every white piece is now active; Black's queenside is asleep." },
        { san: "b5", note: "A desperate bid for counterplay — but it opens even more lines." },
        { san: "Nxb5", keyIdea: "Sacrifice to open lines", note: "The first sacrifice! Morphy gives a knight to blast open the centre against the stranded king." },
        { san: "cxb5", note: "Black accepts." },
        { san: "Bxb5+", note: "Check — and now the rooks are about to crash in. Black can't develop, only defend." },
        { san: "Nbd7", note: "Forced — blocking the check; the knight is pinned and helpless." },
        { san: "O-O-O", keyIdea: "Bring the last rook with tempo", note: "Castling long develops the rook onto the d-file with a deadly pin against the d7-knight. Even castling is an attacking move." },
        { san: "Rd8", note: "Black piles a defender onto the pinned knight." },
        { san: "Rxd7", note: "Removing a defender — the exchange sacrifice clears the way." },
        { san: "Rxd7", note: "Black recaptures, the knight still pinned." },
        { san: "Rd1", keyIdea: "Pile on the pin", note: "The second rook joins, renewing the pressure on the pinned, overloaded d7-rook." },
        { san: "Qe6", note: "A last try to defend and unpin." },
        { san: "Bxd7+", note: "Clearing the way for the finish." },
        { san: "Nxd7", note: "Now only the knight guards the back rank — and it's about to be removed." },
        { san: "Qb8+", keyIdea: "The queen sacrifice", note: "Qb8+!! The final brilliancy — sacrificing the queen to deflect the last defender." },
        { san: "Nxb8", note: "Forced — the knight must capture, abandoning the back rank." },
        { san: "Rd8#", note: "Checkmate. Every white piece took part; Black's queenside never moved. The model attacking game." },
      ],
    },
    {
      type: "puzzle",
      id: "mg-opera-finish",
      title: "Find Morphy's finish",
      blurb: "Two amateurs are about to be immortalized.",
      fen: "4kb1r/p2n1ppp/4q3/4p1B1/4P3/1Q6/PPP2PPP/2KR4 w k - 0 16",
      orientation: "white",
      goal: { type: "mate", inMoves: 2 },
      prompt:
        "White to play and mate in two — the same finish Morphy found. Only the d7-knight guards the back rank.",
      hints: [
        "What's the one piece stopping Rd8 mate?",
        "Deflect it — even at the cost of your queen.",
      ],
      successText:
        "Qb8+!! Nxb8 Rd8# — Morphy's immortal finish. The queen sacrifice removes the last defender, and the rook delivers mate.",
      solution: ["b3b8", "d7b8", "d1d8"],
    },
  ],
};

const evergreen: Lesson = {
  id: "mg-evergreen",
  title: "The Evergreen Game",
  summary: "Anderssen vs Dufresne, 1852 — a romantic-era combination so beautiful it was named 'evergreen'.",
  activities: [
    {
      type: "concept",
      id: "mg-evergreen-concept",
      title: "A combination for the ages",
      blurb: "Sacrifice piles upon sacrifice.",
      body:
        "Adolf Anderssen — the strongest player of his day — produced this against Jean Dufresne in 1852. Wilhelm Steinitz later called it 'evergreen' for its enduring beauty. It opens with a gambit, builds an attack down the centre, and finishes with a cascade of sacrifices culminating in a queen offer.\n\nThe lesson: a lead in development plus open central files lets you throw material at the king, because your remaining pieces arrive faster than the defenders.",
      points: [
        "A gambit buys time and open lines for the attack.",
        "Sacrifices work when your pieces swarm faster than the king can be defended.",
        "Look for the deflection that strips the king's last guard.",
      ],
    },
    {
      type: "replay",
      id: "mg-evergreen-game",
      title: "The Evergreen Game, move by move",
      blurb: "Anderssen vs Dufresne, Berlin 1852.",
      orientation: "white",
      eval: true,
      source: "Anderssen vs Dufresne, Berlin 1852",
      intro:
        "White: Adolf Anderssen. The Evans Gambit explodes into one of history's most beautiful combinations. Watch the eval bar swing wildly — both sides attack — until White's final sacrifices decide it.",
      steps: [
        { san: "e4", note: "Centre." },
        { san: "e5", note: "Symmetry." },
        { san: "Nf3", note: "Develop, attack e5." },
        { san: "Nc6", note: "Defend and develop." },
        { san: "Bc4", note: "The Italian bishop eyes f7." },
        { san: "Bc5", note: "Black mirrors." },
        { san: "b4", keyIdea: "The Evans Gambit", note: "Offering a pawn to deflect the bishop and seize the centre with tempo." },
        { san: "Bxb4", note: "Accepted." },
        { san: "c3", note: "Hitting the bishop and preparing d4 — gaining time." },
        { san: "Ba5", note: "The bishop retreats, eyeing the c3-pawn." },
        { san: "d4", keyIdea: "Build the big centre", note: "Full value for the gambit pawn: a strong centre and a development lead." },
        { san: "exd4", note: "Black grabs back a pawn." },
        { san: "O-O", note: "King safety — and the rook eyes the centre." },
        { san: "d3", note: "Black returns the pawn to blunt White's bishop and grab space." },
        { san: "Qb3", note: "Double attack on f7 and the loose bishop." },
        { san: "Qf6", note: "Defending f7 and developing the queen actively." },
        { san: "e5", note: "Gaining time by attacking the queen and opening lines." },
        { san: "Qg6", note: "The queen sidesteps and eyes White's kingside." },
        { san: "Re1", note: "The rook takes the open e-file, aimed at the centre." },
        { san: "Nge7", note: "Developing toward safety." },
        { san: "Ba3", keyIdea: "Pile up on the pin", note: "The bishop hits e7, pinning along the way and keeping Black's king from castling." },
        { san: "b5", note: "Black lashes out for counterplay." },
        { san: "Qxb5", note: "Snatching the pawn — both sides now play for the attack." },
        { san: "Rb8", note: "Gaining a tempo on the queen." },
        { san: "Qa4", note: "Retreating, still eyeing d7 and the pinned e7-knight." },
        { san: "Bb6", note: "Black activates the bishop and threatens White's centre." },
        { san: "Nbd2", note: "Bringing the last knight toward the kingside attack." },
        { san: "Bb7", note: "Black's bishop joins in, eyeing g2 — counterattack is real." },
        { san: "Ne4", note: "The knight heads for f6/g5; the eval is on a knife's edge." },
        { san: "Qf5", note: "Black defends and counterattacks at once." },
        { san: "Bxd3", note: "Opening lines and threatening Black's queen." },
        { san: "Qh5", note: "The queen swings to the kingside — Black is attacking too." },
        { san: "Nf6+", keyIdea: "The storm breaks", note: "A knight check that wrecks the king's cover and forces the issue." },
        { san: "gxf6", note: "Black must take — opening the g-file toward his own king." },
        { san: "exf6", note: "The pawn rips open the king; White's rook on e1 and bishops aim at the centre." },
        { san: "Rg8", note: "Black counterattacks down the g-file — both kings are in danger." },
        { san: "Rad1", keyIdea: "Bring the last piece", note: "Anderssen quietly develops the final rook into the attack before striking. Every piece must join." },
        { san: "Qxf3", note: "Black grabs a knight and threatens mate on g2 — the position is razor-sharp." },
        { san: "Rxe7+", keyIdea: "The first blow", note: "The combination begins! Rxe7+ rips open the king and removes a key defender." },
        { san: "Nxe7", note: "Forced." },
        { san: "Qxd7+", keyIdea: "The queen sacrifice", note: "Qxd7+!! The immortal move — a queen sacrifice that drags the king into a mating net." },
        { san: "Kxd7", note: "Forced — the king must take." },
        { san: "Bf5+", note: "A quiet bishop check that begins the final geometry." },
        { san: "Ke8", note: "The king is herded back." },
        { san: "Bd7+", note: "The other bishop joins — driving the king to f8." },
        { san: "Kf8", note: "There's no escape now." },
        { san: "Bxe7#", note: "Checkmate. Two bishops and a rook weave the net after the queen sacrifice — the Evergreen finish." },
      ],
    },
  ],
};

const immortal: Lesson = {
  id: "mg-immortal",
  title: "The Immortal Game",
  summary: "Anderssen vs Kieseritzky, 1851 — the most famous sacrifice game in history: a queen, two rooks, and a bishop, all given up for mate.",
  activities: [
    {
      type: "concept",
      id: "mg-immortal-concept",
      title: "Material means nothing, the attack means everything",
      blurb: "Give up everything but the win.",
      body:
        "Played casually between rounds of the first international tournament, this became 'The Immortal Game'. Anderssen sacrifices a bishop, then both rooks, then his queen — ending up with only minor pieces against a full army, and delivers mate.\n\nIt's romantic-era chess at its purest: an extreme demonstration that development and initiative can be worth far more than material, when every piece you keep is aimed at the king.",
      points: [
        "Initiative and attack can outweigh enormous material deficits.",
        "Every sacrifice opens a line or removes a defender — none is random.",
        "Pieces aimed at the king beat pieces sitting idle on the queenside.",
      ],
    },
    {
      type: "replay",
      id: "mg-immortal-game",
      title: "The Immortal Game, move by move",
      blurb: "Anderssen vs Kieseritzky, London 1851.",
      orientation: "white",
      eval: true,
      source: "Anderssen vs Kieseritzky, London 1851",
      intro:
        "White: Adolf Anderssen. By material the engine will show White FAR behind — yet it's White who mates. Watch how every piece Anderssen keeps points at the king while Black's extra pieces sit uselessly at home.",
      steps: [
        { san: "e4", note: "Centre." },
        { san: "e5", note: "Symmetry." },
        { san: "f4", keyIdea: "The King's Gambit", note: "Offering the f-pawn to rip open lines toward Black's king." },
        { san: "exf4", note: "Accepted." },
        { san: "Bc4", note: "Developing, eyeing f7." },
        { san: "Qh4+", note: "A check that costs Black time — the queen will be chased around." },
        { san: "Kf1", note: "White gives up castling but gains time hunting the queen." },
        { san: "b5", note: "A counter-gambit to deflect the bishop." },
        { san: "Bxb5", note: "Accepting — White keeps developing with threats." },
        { san: "Nf6", note: "Developing and eyeing e4/g4." },
        { san: "Nf3", note: "Developing with tempo, hitting the queen." },
        { san: "Qh6", note: "The queen retreats — already Black has spent moves shuffling it." },
        { san: "d3", note: "Opening the dark-squared bishop and supporting e4." },
        { san: "Nh5", note: "Black tries to hold the f4-pawn — but the knight goes offside." },
        { san: "Nh4", note: "Both sides probe the kingside." },
        { san: "Qg5", note: "The queen wanders again, costing Black development." },
        { san: "Nf5", note: "The knight leaps to a dominant square with threats." },
        { san: "c6", note: "Black hits the bishop, gaining a tempo." },
        { san: "g4", keyIdea: "Anderssen attacks anyway", note: "Ignoring threats, White throws a pawn forward to trap the offside knight." },
        { san: "Nf6", note: "The knight retreats." },
        { san: "Rg1", keyIdea: "A rook offered", note: "Calmly developing — and offering the bishop on b5. Material is not the point." },
        { san: "cxb5", note: "Black grabs the bishop." },
        { san: "h4", note: "Driving the queen and opening lines." },
        { san: "Qg6", note: "The queen retreats yet again — Black's pieces are in a tangle." },
        { san: "h5", note: "Gaining time and space, chasing the queen." },
        { san: "Qg5", note: "Nowhere good to go." },
        { san: "Qf3", keyIdea: "Threatening mate", note: "Bringing the queen into the attack, threatening Qxf6 and ideas against f7." },
        { san: "Ng8", note: "The knight is forced all the way home — Black is utterly undeveloped." },
        { san: "Bxf4", note: "Winning back the pawn and developing with a threat to the queen." },
        { san: "Qf6", note: "The queen finally finds a square defending f7 and g7." },
        { san: "Nc3", note: "Developing the last minor piece — every white piece is now active." },
        { san: "Bc5", note: "Black develops with a threat, but it's too late." },
        { san: "Nd5", keyIdea: "Ignoring both rooks", note: "Hitting the queen and threatening mate on c7 — White doesn't care that his rook on a1 hangs." },
        { san: "Qxb2", note: "Black grabs a rook's pawn and attacks the a1-rook." },
        { san: "Bd6", keyIdea: "Offer the second rook", note: "Blocking the c7-mate threat differently — and leaving BOTH rooks hanging. The attack is everything." },
        { san: "Bxg1", note: "Black takes a rook." },
        { san: "e5", note: "Slamming the door — opening lines and shielding against checks while threatening mate." },
        { san: "Qxa1+", note: "Black grabs the other rook with check — but it's the last useful thing he'll do." },
        { san: "Ke2", note: "The king steps up; now Black has no defence to the coming storm." },
        { san: "Na6", note: "Desperately trying to cover c7/b8 — too few defenders, too late." },
        { san: "Nxg7+", keyIdea: "The mating attack", note: "Smashing through. The knight check pulls the king into the net." },
        { san: "Kd8", note: "The king flees." },
        { san: "Qf6+", keyIdea: "The queen sacrifice", note: "Qf6+!! Offering the queen to clear the way and force the knight to block." },
        { san: "Nxf6", note: "Forced — the knight must take, blocking its own king's escape." },
        { san: "Be7#", note: "Checkmate! With only two bishops and a knight, White mates a king surrounded by its own untouched army. Immortal." },
      ],
    },
  ],
};

export const masterGames: Module = {
  id: "master-games",
  title: "Annotated Master Games",
  description:
    "Walk through history's most famous games move by move, with a live eval bar and original annotations: Morphy's Opera Game, the Evergreen, and the Immortal. See ideas play out from the first move to mate.",
  level: "Improver",
  lessons: [overview, opera, evergreen, immortal],
};
